### ISSUE TITLE
Non-null assertion causes linters to fail

### ISSUE THREAD

**Issue by AquaDragon** [kevinddchen/machikoro#102]
One of the uncompleted tasks in #71, the non-null assertion in the various parts of the typescript source code causes the GitHub linter to fail. It can be resolved by running `npm run prettier:fix`, but it appears to be a quick fix and not a long term solution.

This was discussed in https://github.com/kevinddchen/machikoro/issues/97#issuecomment-1524826316.

**Comment by kevinddchen** [comment]
I can expound a little into what I think is the issue.

Typescript does not like when I do unchecked array access using indices, e.g. `array[0]`.

Typescript can go fuck itself.

**Comment by AquaDragon** [comment]
So the non-null assertion operator is the `!` that removes `null` and `undefined` types from an variable. For example, in  https://github.com/kevinddchen/machikoro/blob/main/src/board/MachikoroBoard.tsx#L37, the variable `matchData` which we know not to be `undefined` is passed to `initializeNames()` which then produces an output for `this.names`. If we remove the non-null assertion operator, we would then run into the issue of TypeScript not knowing what to do _if_ `matchData` is `undefined`. 

Almost all workarounds involve explicitly coding the case in which `matchData` is undefined. (See [other examples](https://bobbyhadz.com/blog/typescript-type-undefined-is-not-assignable-to-type).) The intended use of the non-null assertion operator is to make the code less bulky and more elegant after all. But ironically it is considered a bad practice to use it because it could create [runtime errors](https://rules.sonarsource.com/typescript/RSPEC-2966) and other issues. This led to some places using the [no-non-null-assertion rule](https://typescript-eslint.io/rules/no-non-null-assertion/) which our typescript linter is currently enforcing.

I suppose if we want to get rid of the error we have to code in the method to handle the case when a variable is undefined, even if an undefined variable is unlikely. It looks like some of these could be fixed elegantly with one-liners and others are repeats because it involves the repeated use of a single variable. We could give this a shot, but if it makes the code a mess we could just ignore it.
