### ISSUE TITLE
Display a custom message when the game starts

### ISSUE THREAD

**Issue by AquaDragon** [kevinddchen/machikoro#103]
I want to be able to display a custom message right when the game starts. For example in MK2, I want it to display '(Start of initial build phase)' immediately when the game starts. In the future this can be used to include information about the game settings like which version etc.

I spent more than 3 hours today trying to figure out how to do this (and a few hours in another session before `logOtherEvent` was implemented [#92] ) and there has been no progress on this at all 😠 😠 😠

I'm working with the .\src\game\machikoro.ts file. Apparently a line like `Log.logOtherEvent(G, 'TEST')` only works in the list of `const` functions in the Moves section (although it shouldn't be there). I tried creating a move helper but it didn't work. I tried defining it in the setup (Game section after lines 1012) and it didn't work either. I think there has to be a separate function that is not written like a Move `const` function and is called when the game initializes. Unfortunately I'm too noob at typescript and can't tell the difference between `const X: Y => (Z) =>` and `const X = (Z: Y): void =>` to know how to write this correctly.

**Comment by kevinddchen** [comment]
I dont think you are to blame for this. While it is true that the logging stuff mainly happens along with Moves, there is a special case for text that needs to be displayed at the beginning of the game. 

Ive also had issues with trying to display text at the beginning of the game. I had to rely on this: https://github.com/kevinddchen/machikoro/blob/6de7a4cee85bf3cef83955beadfa5ef61aae467e/src/board/TextPanel/Logger.tsx#L90 to display text in the beginning. 

I am not sure if there is a better way. I can look into it tonight, but maybe this is a good place to experiment.
