### ISSUE TITLE
Disable chat for spectators

### ISSUE THREAD

**Issue by AquaDragon** [kevinddchen/machikoro#108]
Here are two interesting features we could implement now that we have spectator mode and a chat:

- Allow spectators to participate in chat. Spectators can enter a name and their typed messages will show up. (right now nothing happens for spectator when they enter typed messages)
- Allow room host or any players to enable/disable spectators from chatting. Mostly for spam control. (First we need to show # of spectators in the room.)

(removed `good first issue` tag as it might be a bit more involved in having to add other features before getting the above to work)

**Comment by kevinddchen** [comment]
Spectators being able to chat is not directly supported, may need some serious workarounds. This is mentioned in the documentation: https://boardgame.io/documentation/#/chat?id=notes

**Comment by AquaDragon** [comment]
Ah, I somehow missed that. I guess we'll disable the chat if it is a spectator for now.
