### ISSUE TITLE
Millionaire's Row expansion

### ISSUE THREAD

**Issue by hongshuozhou** [kevinddchen/machikoro#113]
Hi, does there exist future release plan for millionaire row expansion?

**Comment by BobbytheFatBear** [comment]
I'll second that. The game with millionaire row expansion is much better than Machikoro 2 in my opinion.

**Comment by kevinddchen** [comment]
Ive never played Millionaire Row. Sounds exciting. I can try adding sometime in the future.

**Comment by kevinddchen** [comment]
This is done.

**Comment by hongshuozhou** [comment]
> This is done.

Huge thanks! It is flawless, really appreciate your work.
