### ISSUE TITLE
Remember player's name in lobby

### ISSUE THREAD

**Issue by AquaDragon** [kevinddchen/machikoro#17]
The client has the ability to recall the player's name but the lobby loads a blank field in the "Enter Player Name" input every time it loads. This means that the player has to re-enter their name when they accidentally create a room, leave and return to the lobby or something similar.

Possible solutions are to initialize a blank state at the start of the game or to be able to get the client to check if a name has already been entered at the start.

**Comment by kevinddchen** [comment]
The `name` could be set as a property of `Matchmaker`. This way it can persist when we change between `Room` and `Lobby`.

**Comment by kevinddchen** [comment]
I think much of this can be refactored though. When you are done with the UI elements, I would like to overhaul some of this.
