### ISSUE TITLE
NODE_PATH not recognized on Windows

### ISSUE THREAD

**Issue by AquaDragon** [kevinddchen/machikoro#98]
When following instructions to run Machi Koro locally, NODE_PATH is only recognized on macOS/Linux terminals and not on Windows cmd. (https://stackoverflow.com/a/63270514)

As a result, `npm run serve:dev` or `npm run serve:prod` will generate the following error when running on Windows:
> 'NODE_PATH' is not recognized as an internal or external command,
> operable program or batch file.

One solution to solve this issue is to do the following:
1.  Install the `cross-env` package with `npm install cross-env`
2.  Use `cross-env` with the `serve:dev` and `serve:prod` commands by updating `package.json`, i.e.
    > `"serve:dev": "cross-env NODE_PATH=./src ts-node-dev ./src/server/index.ts",`
    > `"serve:prod": "cross-env NODE_PATH=./src ts-node --transpileOnly ./src/server/index.ts",`

However, checks will need to be performed to see if this solution affects other OS systems. If it doesn't, then other solutions will have to be proposed.

**Comment by kevinddchen** [comment]
@AquaDragon Does this solution work for you on windows?

**Comment by AquaDragon** [comment]
yes

**Comment by kevinddchen** [comment]
OK, let me see if this works for me then. If it does, then we should use it.
